[package]
name = "simple-sdf-compute-shader"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-util = "0.33.0"
winit = "0.28.0"
vulkano-win = "0.33.0"
cgmath = "0.18"
rand = "0.8.4"